services:
  api:
    container_name: api_dev
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
        - DATABASE_URL=file:./db.sqlite
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
      - /app/node_modules
    user: ${CURRENT_UID}
    environment:
      - DATABASE_URL=file:./db.sqlite
      - NODE_ENV=development
