services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./db.sqlite
    restart: unless-stopped
